### ISSUE TITLE
U.S. city names

### ISSUE THREAD

**Issue by mooniker** [eskerda/citybikes-api#10]
I was looking through the ( http://api.citybik.es/networks.json ) with the thought of using this API in a presentation this Friday. I noticed some inconsistencies in the U.S. city names that I thought I'd mention. These aren't super important, but I thought I'd point them out.

I was going to use the commas in the U.S. city names to filter for American cities (it seems only North American cities go by the [city name], [state abbreviation] format, but there are two issues. Pittsburgh is not accompanied by its state (e.g. "Pittsburgh, PA"), like all the other U.S. cities. Also "San Francisco Bay Area, CA" isn't really a name of the city and the bay area is kinda an inconsistent distinction to make here because a number of the other bicycle networks are multijurisdictional. Maybe there's some good rationale for this latter issue though.

Great API all around though. Hope I can think of a cool way to use it.

**Comment by eskerda** [comment]
Hello @mooniker.

Sorry, somehow I had notifications disabled on this repo. You can participate on fixing US names on the following repo https://github.com/eskerda/pybikes

All city names are contained on the data files under https://github.com/eskerda/pybikes/tree/master/pybikes/data

Thanks!
