### ISSUE TITLE
Wrong timestamps

### ISSUE THREAD

**Issue by eskerda** [eskerda/citybikes-api#15]
https://github.com/eskerda/pybikes/issues/141

**Comment by tuxayo** [comment]
> There's an rstrip of zerores on datetimes on the api, hence any date with 0 on seconds will become nothing: https://github.com/eskerda/citybikes-api/blob/master/api/models.py#L116

In what cases is the rstrip() is necessary?

**Comment by eskerda** [comment]
Job precision only reached up to three decimals, so the idea was to get rid of redundant zeroes, like `2015-09-21T19:21:45.096000Z`. That introduced this, which is clearly a bug.

**Comment by tuxayo** [comment]
Job precision ?

**Comment by eskerda** [comment]
Fixed.

> Job precision ?

Either that or how timestamps are being stored, the last three digits on the seconds are redundant, since precision only reaches up to the third one. Such optimization introduced the bug so, being that the case, it does not really matter much if the zeroes are redundant or not.

**Comment by tuxayo** [comment]
> Fixed.

Now the timestamps look like "2016-05-19T17:56:15.383000Z" so I guess it's also deployed, thanks a lot! :-D
