### ISSUE TITLE
standardized "extra" fields

### ISSUE THREAD

**Issue by rolinger** [eskerda/citybikes-api#18]
Hi all, I am quite new to citybik.es, so please forgive me if some of these topics have been covered here or elsewhere.

The first layer of data seems standardized, however, the data in EXTRA is far from it.  Some vendors have it, others don't.  Those that do, some don't provide station address, others provide it as "address:blah blah street" while even others do so as "stAddress1:blah blah street".

I can understand some vendors not having as much "extra" data to share as others, but can any effort be made to at least standardize the EXTRA fields names?  Not having an address is one thing, but customizing code to handle "address" versus "stAddress1" is a whole different ball of wax.

Examples...look at /v2/network/divvy station data versus /v2/network/decobike-miami-beach

network/divvy -> station:

```
empty_slots:6
extra: {altitude: "", city: "Chicago", landMark: "951", lastCommunicationTime: "2016-06-27 07:19:16",…}
     altitude:""
     city:"Chicago"
     landMark:"951"
     lastCommunicationTime:"2016-06-27 07:19:16"
     location:""
     postalCode:"60636"
     stAddress1:"Ashland Ave & 69th St"
     stAddress2:""
     statusKey:1
     statusValue:"In Service"
     testStation:false
     totalDocks:11
     uid:566
free_bikes:5
id:"960d61642e63bd282a2b5353cad11060"
latitude:41.768726
longitude:-87.664069
name:"566 - Ashland Ave & 69th St"
timestamp:"2016-06-27T12:21:33.979000Z"

```
/v2/network/decobike-miami-beach

```
empty_slots:12
extra:{address: "Museum Park", uid: "648"}
     address:"Museum Park"
     uid:"648"
free_bikes:4
id:"005ba8ae8b98a8d2f3045ba3e48b459c"
latitude:25.784943
longitude:-80.18683
name:"648 - Museum Park"
timestamp:"2016-06-27T12:19:26.872000Z"
```

**Comment by rolinger** [comment]
I stand corrected, the top level station.name is not standardized.  Some have it as an street address only, a full street/city/state/zip address and others have is a combo of one of the first two prefixed by a uid.

**Comment by eskerda** [comment]
Feel free to reach out to github.com/eskerda/pybikes (the actual data source). There you will find where the fields on extra come from, and propose ways to improve them or make them more consistent across networks.
