### ISSUE TITLE
Internal Server Error on the API

### ISSUE THREAD

**Issue by tuxayo** [eskerda/citybikes-api#21]
https://api.citybik.es/
https://api.citybik.es/v2/
https://api.citybik.es/v2/networks/le-velo
http://api.citybik.es/v2/networks/le-velo

**Comment by eskerda** [comment]
Can you send an email instead of opening an issue?

This was related to a forced restart, provider patching `spectre` and shit

**Comment by tuxayo** [comment]
Noted, thanks :)
