### ISSUE TITLE
Network location latitude/longitude are not all the same type

### ISSUE THREAD

**Issue by dcramps** [eskerda/citybikes-api#7]
Some are strings, some are floats.
eg:

Floating point
http://api.citybik.es/v2/networks/bixi-toronto
```
location: {
    city: "Toronto, ON",
    country: "CA",
    latitude: 43.653226,
    longitude: -79.3831843
}
```

String
http://api.citybik.es/v2/networks/onroll-a-rua
```
location: {
   city: "A Rúa",
   country: "ES",
   latitude: "42.392049",
   longitude: "-7.114634"
}
```

**Comment by eskerda** [comment]
Fixed it: https://github.com/eskerda/pybikes/commit/118ef940b7c55b11cbc665edd3f74cf800931a9b
